### ISSUE TITLE
SConstruct use uncommon method to add lib

### ISSUE THREAD

**Issue by floli** [precice/elastictube1d#6]
SConstruct contains that line:

```
if not env["boost_inst"]:
   boostRootPath = checkset_var('PRECICE_BOOST_ROOT', "./src")
   env.AppendUnique(CXXFLAGS = ['-isystem', '-lrt', boostRootPath]) # -isystem supresses compilation warnings for boost headers
```
- Why is librt not added by config.CheckLib()?
- What is bootsRootPath about after lrt? Use LIBPATH to set path to libraries.
- Compilation does not work using boost_inst=off with PRECICE_BOOT_ROOT set. (of course, since it can't find boost)

**Comment by uekerman** [comment]
not sure if i fully understand your questions, also i am no extreme scons expert.
but what i know is that boost_inst=off means that we do not link against the boost libs, but copy the headers directly to src. does that help?
on the atsccs machines, e.g. i do use PRECICE_BOOST_ROOT and boost_inst=off.
anyway, feel free to adjust things if you think they are not done the right way. 
i think having both options (link against boost lib and use header-only) is important since we had issues with both when combining with certain gcc versions.

**Comment by floli** [comment]
> but what i know is that boost_inst=off means that we do not link against the boost libs, but copy the headers directly to src. does that help?

There is no code to copy boost in the elastictube1d/SConstruct file.
- `scons boost_inst=on python=off` works if preCICE itself is built with python=off
- `scons boost_inst=on python=on` works.
- `scons boost_inst=off` does not work and from I see in the SConstruct file it can't possibly work, because the boost files are not copied to some source directory.

I've done some fixes but imho boost_inst=off still can't work in the general case.

**Comment by uekerman** [comment]
ah, this is about the elastic-tube, sry i completely missed. sry.
should be fine then.

**Comment by MakisH** [comment]
No longer relevant since a while, as we are now using CMake.

**Comment by floli** [comment]
lol, some unweary ghost from the past :-)
